# Generated by cucumber-sinatra. (2012-03-17 19:46:55 +0400)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'main.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'r18n-core'

Capybara.app = Scanty::Blog

class ScantyBlogWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ScantyBlogWorld.new
end
